
#            app:
#                dataSource:
#                  postgres:
#                    port: 5432
#                  username: postgres
#                  password: bobah
#                  host: localhost
#                  databaseName: test
#                  jdbc-url: jdbc:postgresql://192.168.99.100:5432/postgres